# config.py
from os import getenv

from dotenv import load_dotenv

load_dotenv()

MYSQL_DATABASE_USER = getenv('MYSQL_DATABASE_USER') 
MYSQL_DATABASE_PASSWORD = getenv('MYSQL_DATABASE_PASSWORD') 
MYSQL_DATABASE_DB = getenv('MYSQL_DATABASE_DB') 
MYSQL_DATABASE_HOST = getenv('MYSQL_DATABASE_HOST')
MYSQL_DATABASE_PORT = getenv('MYSQL_DATABASE_PORT')
assert MYSQL_DATABASE_USER
assert MYSQL_DATABASE_PASSWORD
assert MYSQL_DATABASE_DB
assert MYSQL_DATABASE_HOST
assert MYSQL_DATABASE_PORT

# use the key
print(MYSQL_DATABASE_USER)
print(MYSQL_DATABASE_PASSWORD)
print(MYSQL_DATABASE_DB)
print(MYSQL_DATABASE_HOST)
print(MYSQL_DATABASE_PORT)